repos:
  # Secret scanning with gitleaks (Docker-based for Windows)
  - repo: local
    hooks:
      - id: gitleaks
        name: Detect secrets with gitleaks
        description: Scan for hardcoded secrets, API keys, and credentials
        entry: pwsh -File gitleaks.ps1 detect --source . --no-git -v
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: detect-private-key

  - repo: local
    hooks:
      - id: no-dbt-artifacts
        name: block dbt build artifacts
        entry: >
          bash -c 'git diff --cached --name-only |
          grep -E "analytics/dbt/(dbt_packages|target|package-lock\.yml|logs|manifest\.json|run_results\.json|catalog\.json)" &&
          echo "❌ Do not commit dbt artifacts. Run: git reset HEAD <file>" &&
          exit 1 || exit 0'
        language: system
