version: 1
disable_existing_loggers: False

formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
  
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/api.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: no
  
  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: no
  
  uvicorn.access:
    level: INFO
    handlers: [console]
    propagate: no
  
  app:
    level: INFO
    handlers: [console]
    propagate: no
  
  sqlalchemy.engine:
    level: WARNING
    handlers: [console]
    propagate: no

root:
  level: INFO
  handlers: [console]
