applylens:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('BQ_PROJECT', 'applylens-analytics') }}"
      dataset: applylens
      threads: 4
      keyfile: "{{ env_var('BQ_KEYFILE', 'applylens-ci.json') }}"
      location: US
      priority: interactive
      timeout_seconds: 300
      maximum_bytes_billed: 1000000000  # 1GB limit
    
    ci:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: applylens
      threads: 4
      keyfile_json: "{{ env_var('BQ_SA_JSON') }}"
      location: US
      priority: interactive
      timeout_seconds: 300
    
    local_prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: applylens
      threads: 8  # More threads for production
      keyfile: "applylens-ci.json"  # Use local file
      location: US
      priority: interactive
      timeout_seconds: 600  # Longer timeout for prod
      maximum_bytes_billed: 10000000000  # 10GB limit for production
    
    # Production profile for Fivetran + warehouse operations
    prod:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('GCP_PROJECT') }}"
      dataset: gmail_raw_stg
      threads: 4
      keyfile_json: "{{ env_var('GCP_SA_JSON') }}"
      location: US
      priority: interactive
      timeout_seconds: 600
      maximum_bytes_billed: 10000000000
