name: E2E
on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
        shardsTotal: [3]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'apps/web/package.json'
      - name: Install deps
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Build
        run: npm run build
      - name: Run tests (sharded)
        env:
          CI: 'true'
        run: |
          npx playwright test --shard=${{ matrix.shard }}/${{ matrix.shardsTotal }} --reporter=list,junit,html
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-shard-${{ matrix.shard }}
          path: apps/web/playwright-report
          if-no-files-found: ignore
      - name: Upload junit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.shard }}
          path: apps/web/reports/junit.xml
          if-no-files-found: ignore
