name: E2E
on:
  push:
    branches: [main, UI-polish]
  pull_request:

jobs:
  e2e-root:
    name: E2E Tests (Root)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build web app
        run: pnpm --filter applylens-web build
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm test:e2e
        env:
          CI: true
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7

  e2e-web:
    name: E2E Tests (Web Workspace)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
        shardsTotal: [3]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'apps/web/package.json'
      - name: Install deps
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Build
        run: npm run build
      - name: Run tests (sharded)
        env:
          CI: 'true'
        run: |
          npx playwright test --shard=${{ matrix.shard }}/${{ matrix.shardsTotal }} --reporter=list,junit,html
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-shard-${{ matrix.shard }}
          path: apps/web/playwright-report
          if-no-files-found: ignore
      - name: Upload junit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.shard }}
          path: apps/web/reports/junit.xml
          if-no-files-found: ignore
