name: Prod Smoke Tests (Read-only)

# Manual trigger only - never runs automatically
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  smoke:
    name: Run @prodSafe tests on production
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        working-directory: apps/web
        run: pnpm exec playwright install --with-deps chromium

      - name: Check for prod storage state
        id: check_state
        working-directory: apps/web
        run: |
          if [ ! -f "tests/.auth/prod.json" ]; then
            echo "❌ prod.json not found!"
            echo "Please create it with: pnpm exec tsx tests/setup/save-prod-state.ts"
            exit 1
          fi
          echo "✓ prod.json exists"

      - name: Run @prodSafe tests on production
        working-directory: apps/web
        env:
          E2E_BASE_URL: https://applylens.app
          CI: "1"
        run: pnpm test:e2e

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-prod-smoke
          path: apps/web/playwright-report/
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results-prod-smoke
          path: apps/web/test-results/
          retention-days: 7

      - name: Comment on success
        if: success()
        run: |
          echo "✅ Production smoke tests passed!"
          echo "All @prodSafe tests ran successfully in read-only mode."

      - name: Comment on failure
        if: failure()
        run: |
          echo "❌ Production smoke tests failed!"
          echo "Check the uploaded artifacts for details."
